# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Download and deploy ASP app to Azure Web App - demo4selvan

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      artifactid:
        required: true
        type: string
        default: '100'

jobs:

  deploy:
    runs-on: windows-latest
    

    steps:

    - name: Call GH API
      run: |
          $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
          $headers.Add("Accept", "application/vnd.github+json")
          $headers.Add("X-GitHub-Api-Version", "2022-11-28")
          $headers.Add("Authorization", '${{ secrets.GHToken }}')

          $response = Invoke-RestMethod 'https://api.github.com/repos/selvan123/app-service-web-dotnet-get-started/actions/artifacts'
          

          foreach($res in $response.artifacts)
          {
            #Write-Host $res.name
              if ($res.name -eq '${{ inputs.artifactid }}')
              {
                  #Write-Host $res.name
                  Write-Host $res.archive_download_url                  
                  $filename = '${{ inputs.artifactid }}.zip'
                  Write-Host $filename
                  $response = Invoke-WebRequest $res.archive_download_url -Method 'GET' -Headers $headers -OutFile $filename
                  Get-ChildItem
              } 
          }     

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SCDDemo'
        slot-name: 'Production'
        publish-profile: ${{ secrets.SCDDemoAZUREAPPSERVICE_PUBLISHPROFILE }}
        package: '${{ inputs.artifactid }}.zip'

   